### PR TITLE
 Out-of-the-box transformations for proxied requests

### LINKED ISSUE #65: Out-of-the-box transformations for proxied requests
- [ ] path (e.g. prefix addition or removal)
- [ ] query (e.g. transform query param into path param)
- [ ] headers/trailers (filtering and modification)
- [ ] body (e.g. read JSON fully and modify fields)

### PR DESCRIPTION
**Pull request by tsegismont**
Closes #65

### CODE REVIEW

**Comment by tsegismont** [comment]
@wzy1935 I've rebased the PR. I found in test code a few calls to Java 21 API. Make sure to configure your IDE so that the target API is Java 11 only.

**Comment by tsegismont** [comment]
@wzy1935 2 tests are not passing on Windows CI, can you take a look?

**Comment by wzy1935** [comment]
okay, I'm checking

**Comment by wzy1935** [comment]
The PR for a possible fix is attached. It works locally, but I am not sure because I cannot access to the CI

**Comment by tsegismont** [comment]
@wzy1935 it looks like your last PR did the trick, thank you!

**Pull request merged**
