### PR TITLE
add tests for special websocket upgrade request

### PR DESCRIPTION
**Pull request by machine424**
Motivation:

See: https://github.com/eclipse-vertx/vertx-http-proxy/issues/62

Conformance:

You should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by vietj** [comment]
So we expect this new test to fail ?

**Comment by machine424** [comment]
I rebased to get your latest fixes regarding `parseHostAndPort`

Yes `testWebSocketMultiValueConnHeader` should fail, `testWebSocketUniqueValueConnHeader` is just a "positive control" and we'll get rid of it.

**Comment by tsegismont** [comment]
@machine424 can you please sign the Eclipse Contributor Agreement and sign-off your commits? Thanks

**Review by tsegismont — COMMENTED** [review]
Than you @machine424 , can you provide a fix similar to what we have in the `vertx-web` project?

**Comment by tsegismont** [comment]
Superseded by #63

**Comment by tsegismont** [comment]
Thank you @machine424 

I went ahead and sent #63 because we'd like to release 4.5.3 today

**Pull request closed without merging**
